server:
  port: 8050

spring:
  application:
    name: jt-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka

zuul:
  ignoredServices: '*'
  routes:
    app-jt-sso:
      path: /jt/sso/**
      serviceId: jt-sso
 
      
      
      