server:
  port: 8070

spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://176.20.12.201:3306/mybatisdb
        username: root
        password: root

mybatis:
  typeAliasesPackage: cn.tedu.ssm.pojo
  mapperLocations: classpath:mappers/*.xml

logging:
  level: 
    cn.tedu.ssm.mapper: debug
